// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: src/Pacco.Services.Operations.GrpcClient/Operations.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Services.Operations {
  public static partial class GrpcOperationsService
  {
    static readonly string __ServiceName = "Services.Operations.GrpcOperationsService";

    static readonly grpc::Marshaller<global::Services.Operations.GetOperationRequest> __Marshaller_Services_Operations_GetOperationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.Operations.GetOperationRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Services.Operations.GetOperationResponse> __Marshaller_Services_Operations_GetOperationResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.Operations.GetOperationResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Services.Operations.Empty> __Marshaller_Services_Operations_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Services.Operations.Empty.Parser.ParseFrom);

    static readonly grpc::Method<global::Services.Operations.GetOperationRequest, global::Services.Operations.GetOperationResponse> __Method_GetOperation = new grpc::Method<global::Services.Operations.GetOperationRequest, global::Services.Operations.GetOperationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOperation",
        __Marshaller_Services_Operations_GetOperationRequest,
        __Marshaller_Services_Operations_GetOperationResponse);

    static readonly grpc::Method<global::Services.Operations.Empty, global::Services.Operations.GetOperationResponse> __Method_SubscribeOperations = new grpc::Method<global::Services.Operations.Empty, global::Services.Operations.GetOperationResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeOperations",
        __Marshaller_Services_Operations_Empty,
        __Marshaller_Services_Operations_GetOperationResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Services.Operations.OperationsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GrpcOperationsService</summary>
    [grpc::BindServiceMethod(typeof(GrpcOperationsService), "BindService")]
    public abstract partial class GrpcOperationsServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Services.Operations.GetOperationResponse> GetOperation(global::Services.Operations.GetOperationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task SubscribeOperations(global::Services.Operations.Empty request, grpc::IServerStreamWriter<global::Services.Operations.GetOperationResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GrpcOperationsService</summary>
    public partial class GrpcOperationsServiceClient : grpc::ClientBase<GrpcOperationsServiceClient>
    {
      /// <summary>Creates a new client for GrpcOperationsService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GrpcOperationsServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GrpcOperationsService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GrpcOperationsServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GrpcOperationsServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GrpcOperationsServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Services.Operations.GetOperationResponse GetOperation(global::Services.Operations.GetOperationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOperation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Services.Operations.GetOperationResponse GetOperation(global::Services.Operations.GetOperationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOperation, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Services.Operations.GetOperationResponse> GetOperationAsync(global::Services.Operations.GetOperationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOperationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Services.Operations.GetOperationResponse> GetOperationAsync(global::Services.Operations.GetOperationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOperation, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Services.Operations.GetOperationResponse> SubscribeOperations(global::Services.Operations.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscribeOperations(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Services.Operations.GetOperationResponse> SubscribeOperations(global::Services.Operations.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribeOperations, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GrpcOperationsServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GrpcOperationsServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GrpcOperationsServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetOperation, serviceImpl.GetOperation)
          .AddMethod(__Method_SubscribeOperations, serviceImpl.SubscribeOperations).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GrpcOperationsServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetOperation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Services.Operations.GetOperationRequest, global::Services.Operations.GetOperationResponse>(serviceImpl.GetOperation));
      serviceBinder.AddMethod(__Method_SubscribeOperations, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Services.Operations.Empty, global::Services.Operations.GetOperationResponse>(serviceImpl.SubscribeOperations));
    }

  }
}
#endregion
